// examples/react/imports/ui/components/Info.jsx
import React from 'react';
import { useFind, useSubscribe } from '@meteor-vite/react-meteor-data';
import { LinksCollection } from '../../api/links/links';

export const Info = () => {
    try {
        const isLoading = useSubscribe('links');
        const links = useFind(() => LinksCollection.find());
        if (isLoading()) {
            return <div>Loading...</div>;
        }

        return (
            <div>
                <h2>Learn Meteor!</h2>
                <ul>{links.map(
                    link => <li key={link._id}>
                        <a href={link.url} target="_blank">{link.title}</a>
                    </li>,
                )}</ul>
            </div>
        );

    } catch (error) {
        return (
            <div>
                <h1>Exception while calling React Meteor Data</h1>
                <p>
                    Todo: Vite and Meteor's React versions appear to be slightly different. Importing React with CJS
                    syntax seems to resolve the issue.
                </p>
                <pre>{error.stack}</pre>
            </div>
        );
    }
};

// examples/vue-ssr/imports/ui/components/Info.vue
<script setup>
import { LinksCollection } from '/imports/api/links'
import VueMeteor from '/imports/ui/lib/VueMeteor';

VueMeteor.subscribe('links');
const links = VueMeteor.computed(() => LinksCollection.find());
</script>

<template>
  <h2 class="text-xl my-6 font-semibold">Learn Meteor!</h2>
  <ul class="list-disc underline">
    <li v-for="link of links" :key="link._id" class="hover:text-green-700">
      <a :href="link.url" target="_blank">{{ link.title }}</a>
    </li>
  </ul>
</template>
